<?php

namespace App\Services;

use App\Models\Workflow;
use App\Services\AgentComposeService;

class WorkflowExportService
{
    public function __construct(
        private AgentComposeService $agentCompose,
    ) {}

    public function exportJson(Workflow $workflow): array
    {
        $workflow->loadMissing(['steps.agent', 'edges', 'project']);

        return [
            'format' => 'orkestr-workflow',
            'version' => '1.0',
            'workflow' => [
                'name' => $workflow->name,
                'slug' => $workflow->slug,
                'description' => $workflow->description,
                'trigger_type' => $workflow->trigger_type,
                'trigger_config' => $workflow->trigger_config,
                'status' => $workflow->status,
                'context_schema' => $workflow->context_schema,
                'termination_policy' => $workflow->termination_policy,
                'config' => $workflow->config,
            ],
            'steps' => $workflow->steps->map(fn ($step) => [
                'id' => $step->uuid,
                'type' => $step->type,
                'name' => $step->name,
                'agent' => $step->agent ? [
                    'name' => $step->agent->name,
                    'slug' => $step->agent->slug,
                    'role' => $step->agent->role,
                    'model' => $step->agent->model,
                ] : null,
                'config' => $step->config,
                'position' => ['x' => $step->position_x, 'y' => $step->position_y],
            ])->toArray(),
            'edges' => $workflow->edges->map(fn ($edge) => [
                'source' => $workflow->steps->firstWhere('id', $edge->source_step_id)?->uuid,
                'target' => $workflow->steps->firstWhere('id', $edge->target_step_id)?->uuid,
                'condition' => $edge->condition_expression,
                'label' => $edge->label,
                'priority' => $edge->priority,
            ])->toArray(),
        ];
    }

    public function exportLangGraph(Workflow $workflow): string
    {
        $workflow->loadMissing(['steps.agent', 'edges']);

        $lines = [];
        $lines[] = '# LangGraph workflow definition';
        $lines[] = '# Generated by Orkestr';
        $lines[] = '';
        $lines[] = 'name: ' . $workflow->name;
        $lines[] = 'description: ' . ($workflow->description ?? '');
        $lines[] = '';
        $lines[] = 'nodes:';

        foreach ($workflow->steps as $step) {
            $lines[] = '  - id: ' . $step->uuid;
            $lines[] = '    name: ' . $step->name;
            $lines[] = '    type: ' . $this->mapToLangGraphType($step->type);

            if ($step->agent) {
                $lines[] = '    agent:';
                $lines[] = '      name: ' . $step->agent->name;
                $lines[] = '      model: ' . ($step->agent->model ?? 'default');
                $lines[] = '      system_message: |';
                $prompt = $step->agent->getEffectiveSystemPrompt();
                foreach (explode("\n", $prompt) as $promptLine) {
                    $lines[] = '        ' . $promptLine;
                }
            }
            $lines[] = '';
        }

        $lines[] = 'edges:';
        foreach ($workflow->edges as $edge) {
            $sourceUuid = $workflow->steps->firstWhere('id', $edge->source_step_id)?->uuid ?? '';
            $targetUuid = $workflow->steps->firstWhere('id', $edge->target_step_id)?->uuid ?? '';

            $lines[] = '  - source: ' . $sourceUuid;
            $lines[] = '    target: ' . $targetUuid;
            if ($edge->condition_expression) {
                $lines[] = '    condition: "' . addslashes($edge->condition_expression) . '"';
            }
            if ($edge->label) {
                $lines[] = '    label: ' . $edge->label;
            }
        }

        return implode("\n", $lines) . "\n";
    }

    public function exportCrewAI(Workflow $workflow): array
    {
        $workflow->loadMissing(['steps.agent', 'edges']);

        $agents = [];
        $tasks = [];

        foreach ($workflow->steps->where('type', 'agent') as $step) {
            if (! $step->agent) {
                continue;
            }

            $agents[] = [
                'role' => $step->agent->role ?? $step->agent->name,
                'goal' => $step->agent->objective_template ?? 'Complete the assigned task',
                'backstory' => $step->agent->getEffectiveSystemPrompt(),
                'verbose' => true,
                'allow_delegation' => $step->agent->can_delegate ?? false,
            ];

            $tasks[] = [
                'description' => $step->name,
                'agent' => $step->agent->role ?? $step->agent->name,
                'expected_output' => $step->agent->objective_template ?? 'Task completed',
            ];
        }

        return [
            'crew' => [
                'name' => $workflow->name,
                'description' => $workflow->description,
                'process' => $this->inferCrewProcess($workflow),
                'verbose' => true,
            ],
            'agents' => $agents,
            'tasks' => $tasks,
        ];
    }

    private function mapToLangGraphType(string $type): string
    {
        return match ($type) {
            'start' => 'START',
            'end' => 'END',
            'agent' => 'agent',
            'condition' => 'conditional',
            'parallel_split' => 'parallel',
            'parallel_join' => 'join',
            'checkpoint' => 'human_in_the_loop',
            default => 'passthrough',
        };
    }

    private function inferCrewProcess(Workflow $workflow): string
    {
        $hasParallel = $workflow->steps->whereIn('type', ['parallel_split', 'parallel_join'])->isNotEmpty();

        return $hasParallel ? 'hierarchical' : 'sequential';
    }
}
