{{- if and .Values.mariadb.enabled .Values.mariadb.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "orkestr.mariadb.fullname" . }}-data
  labels:
    {{- include "orkestr.mariadb.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.mariadb.persistence.storageClass }}
  storageClassName: {{ .Values.mariadb.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.mariadb.persistence.size }}
{{- end }}
